server:
  port: 8443
  ssl:
    enabled: true
    key-alias: https-springboot
    key-store-type: JKS
    #key-store-type: PKCS12
    key-store: classpath:https-springboot.jks
    key-store-password: password