server:
  port: 8443
  ssl:
    enabled: true
    key-alias: https-springboot
    key-store-type: JKS
    #key-store-type: PKCS12
    key-store: classpath:https-springboot.jks
    key-store-password: password
    ciphers: :ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
    protocol: TLSv1.2